### ISSUE TITLE
tests fail when installing new master on top of old conda distribution

### ISSUE THREAD

**Issue by cbayly13** [open-forcefield-group/openforcefield#63]
nothing works and even tests fail after trying to install the new openforcefield master. My installation went like this:
conda create -c conda-forge -c omnia -n openff_2017sep python=3.5 openforcefield
source activate openff_2017sep
pip install jupyter
pip install OpenEye-toolkits
cd openforcefield
pip install -e ./

The traceback I get with tests all end up with the same KeyError on 'return self._nodes[n]', example:
======================================================================
ERROR: Check embedded atom parsing works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bayly/BaylyData/projects/forcefield/openforcefield/openforcefield/tests/test_chemicalenvironment.py", line 213, in test_embedded_atoms_smirks
    env = ChemicalEnvironment(smirks)
  File "/Users/bayly/BaylyData/projects/forcefield/openforcefield/openforcefield/typing/chemistry/environment.py", line 473, in __init__
    if not self.isValid():
  File "/Users/bayly/BaylyData/projects/forcefield/openforcefield/openforcefield/typing/chemistry/environment.py", line 486, in isValid
    smirks = self._asSMIRKS()
  File "/Users/bayly/BaylyData/projects/forcefield/openforcefield/openforcefield/typing/chemistry/environment.py", line 711, in _asSMIRKS
    initialAtom = self.getAtoms()[0]
  File "/Users/bayly/miniconda/envs/openff_2017sep/lib/python3.5/site-packages/networkx/classes/reportviews.py", line 178, in __getitem__
    return self._nodes[n]
KeyError: 0

**Comment by jchodera** [comment]
Something upstream may have changed. The last travis build was [14 days ago](https://travis-ci.org/open-forcefield-group/openforcefield/builds/277487572). I've enabled nightly builds so we catch issues more quickly.

**Comment by jchodera** [comment]
I can reproduce this issue. Debugging...

**Comment by jchodera** [comment]
I'm betting it's [networkx](https://anaconda.org/conda-forge/networkx/files), which was just updated to 2.0 on `conda-forge` 12 days ago (since our last travis test).

**Comment by jchodera** [comment]
Pinning `networkx` to 1.11 fixes the issue:
```bash
conda install --yes networkx==1.11
```
I'll create a PR to change the `devtools/` recipe, but we should also pin this in the conda recipe.

**Comment by jchodera** [comment]
Let me know if there are other issues, @cbayly13!
